controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (controller.down.isPressed()) {
        animation.runImageAnimation(
        mySprite,
        [img`
            ....f........f..........
            ...f1f......f1f.........
            ...f11f....f11f.........
            ..f11f......f11f........
            ..f11ffffffff11f........
            ..f11f111111f11f........
            ...f1111111111f.........
            ...f1111111111f.........
            ...f11ff11ff11f.........
            ...f11ff11ff11f.........
            ...f11ff11ff11f.........
            ....f11111111f..........
            .....cbbbbbbf...........
            .ccccdcffbbbf...........
            cdddddcfffbbf...........
            .ccccdcffffbf...........
            .....cff..ff............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ..f........f............
            .f1f......f1f...........
            .f11f....f11f...........
            f11f......f11f..........
            f11ffffffff11f..........
            f11f111111f11f..........
            .f1111111111f...........
            .f1111111111f...........
            .f11ff11ff11f...........
            .f11ff11ff11f...........
            .f11ff11ff11f...........
            ..f11111111f............
            ...fbbbbbbf.............
            ...fbbbfbbf.............
            ...fbbffbbf.............
            ...fbcccfbf.............
            ....fcdcff..............
            ....cddc................
            ...cddc.................
            ..cddc..................
            ..cdc...................
            ..cc....................
            ........................
            ........................
            `,img`
            ..f........f............
            .f1f......f1f...........
            .f11f....f11f...........
            f11f......f11f..........
            f11ffffffff11f..........
            f11f111111f11f..........
            .f1111111111f...........
            .f1111111111f...........
            .f11ff11ff11f...........
            .f11ff11ff11f...........
            .f11ff11ff11f...........
            ..f11111111f............
            ...fbbbbbbf.............
            ...fbbbfbbf.............
            ...fbbffbbf.............
            ...fbfcccbf.............
            ....fcc1cc..............
            ......c1c...............
            ......c1c...............
            ......c1c...............
            ......c1c...............
            .......c................
            ........................
            ........................
            `,img`
            ..f........f............
            .f1f......f1f...........
            .f11f....f11f...........
            f11f......f11f..........
            f11ffffffff11f..........
            f11f111111f11f..........
            .f1111111111f...........
            .f1111111111f...........
            .f11ff11ff11f...........
            .f11ff11ff11f...........
            .f11ff11ff11f...........
            ..f11111111f............
            ...fbbbbbbc.............
            ...fbbbffcdcccc.........
            ...fbbfffcdddddc........
            ...fbffffcdcccc.........
            ....ff..ffc.............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        false
        )
    } else {
        if (controller.right.isPressed() && !(controller.left.isPressed())) {
            animation.runImageAnimation(
            mySprite,
            [img`
                .....f1f..f1f...........
                .....f11ff11f...........
                ....f11fff11f...........
                ....f1111111f...........
                ...f111111111f..........
                ...f111ff1ff1f..........
                ...f111ff1ff1f..........
                ...f111ff1ff1f.cc.......
                ...f111111111fcdc.......
                ....f1111111fcddc.......
                .....fbbbbbfcddc........
                .....fbbbbfcddc.........
                .....fbbbffcdc..........
                .....fbbfffccc..........
                .....fbbffff............
                ......ff.ff.............
                `,img`
                .....f1f..f1f...........
                .....f11ff11f...........
                ....f11fff11f...........
                ....f1111111f...........
                ...f111111111f..........
                ...f111ff1ff1f..........
                ...f111ff1ff1f..........
                ...f111ff1ff1f..........
                ...f111111111f..cc......
                ....f1111111f.ccdc......
                .....fbbbbbfccddcc......
                .....fbbbbfcdddc........
                .....fbbbffcdcc.........
                .....fbbfffccc..........
                .....fbbfff.............
                ......ff.ff.............
                `,img`
                .....f1f..f1f...........
                .....f11ff11f...........
                ....f11fff11f...........
                ....f1111111f...........
                ...f111111111f..........
                ...f111ff1ff1f..........
                ...f111ff1ff1f..........
                ...f111ff1ff1f..........
                ...f111111111f..........
                ....f1111111f...........
                .....fbbbbbc............
                .....fbbbbfccccccc......
                .....fbbbffcddddd.......
                .....fbbfffccccc........
                .....fbbfffc............
                ......ff.ff.............
                `,img`
                .....f1f..f1f...........
                .....f11ff11f...........
                ....f11fff11f...........
                ....f1111111f...........
                ...f111111111f..........
                ...f111ff1ff1f..........
                ...f111ff1ff1f..........
                ...f111ff1ff1f..........
                ...f111111111f..........
                ....f1111111f...........
                .....fbbbbbf............
                .....fbbbbccc...........
                .....fbbbfcdc...........
                .....fbbffcddc..........
                .....fbbfffcddc.........
                ......ff.ff.cddc........
                `],
            100,
            false
            )
            pause(500)
            mySprite.setImage(img`
                . . . . . f 1 f . . f 1 f . . . 
                . . . . . f 1 1 f f 1 1 f . . . 
                . . . . f 1 1 f f f 1 1 f . . . 
                . . . . f 1 1 1 1 1 1 1 f . . . 
                . . . f 1 1 1 1 1 1 1 1 1 f . . 
                . . . f 1 1 1 f f 1 f f 1 f . . 
                . . . f 1 1 1 f f 1 f f 1 f . . 
                . . . f 1 1 1 f f 1 f f 1 f . . 
                . . . f 1 1 1 1 1 1 1 1 1 f . . 
                . . . . f 1 1 1 1 1 1 1 f . . . 
                . . . . . f b b b b b f . . . . 
                . . . . . f b b b b b f . . . . 
                . . . . . f b b f b b f . . . . 
                . . . . . f b f f b b f . . . . 
                . . . . . f b f f f b f . . . . 
                . . . . . . f f . f f . . . . . 
                `)
        } else {
            if (controller.left.isPressed() && !(controller.right.isPressed())) {
                animation.runImageAnimation(
                mySprite,
                [img`
                    ...........f1f..f1f.....
                    ...........f11ff11f.....
                    ...........f11fff11f....
                    ...........f1111111f....
                    ..........f111111111f...
                    ..........f1ff1ff111f...
                    ..........f1ff1ff111f...
                    .......cc.f1ff1ff111f...
                    .......cdcf111111111f...
                    .......cddcf1111111f....
                    ........cddcfbbbbbf.....
                    .........cddcfbbbbf.....
                    ..........cdcffbbbf.....
                    ..........cccfffbbf.....
                    ............ffffbbf.....
                    .............ff.ff......
                    `,img`
                    ...........f1f..f1f.....
                    ...........f11ff11f.....
                    ...........f11fff11f....
                    ...........f1111111f....
                    ..........f111111111f...
                    ..........f1ff1ff111f...
                    ..........f1ff1ff111f...
                    ..........f1ff1ff111f...
                    ......cc..f111111111f...
                    ......cdcc.f1111111f....
                    ......ccddccfbbbbbf.....
                    ........cdddcfbbbbf.....
                    .........ccdcffbbbf.....
                    ..........cccfffbbf.....
                    .............fffbbf.....
                    .............ff.ff......
                    `,img`
                    ...........f1f..f1f.....
                    ...........f11ff11f.....
                    ...........f11fff11f....
                    ...........f1111111f....
                    ..........f111111111f...
                    ..........f1ff1ff111f...
                    ..........f1ff1ff111f...
                    ..........f1ff1ff111f...
                    ..........f111111111f...
                    ...........f1111111f....
                    ............cbbbbbf.....
                    ......cccccccfbbbbf.....
                    .......dddddcffbbbf.....
                    ........cccccfffbbf.....
                    ............cfffbbf.....
                    .............ff.ff......
                    `,img`
                    ...........f1f..f1f.....
                    ...........f11ff11f.....
                    ...........f11fff11f....
                    ...........f1111111f....
                    ..........f111111111f...
                    ..........f1ff1ff111f...
                    ..........f1ff1ff111f...
                    ..........f1ff1ff111f...
                    ..........f111111111f...
                    ...........f1111111f....
                    ............fbbbbbf.....
                    ...........cccbbbbf.....
                    ...........cdcfbbbf.....
                    ..........cddcffbbf.....
                    .........cddcfffbbf.....
                    ........cddc.ff.ff......
                    `],
                100,
                false
                )
                pause(500)
                mySprite.setImage(img`
                    . . f 1 f . . f 1 f . . . . . . 
                    . . f 1 1 f f 1 1 f . . . . . . 
                    . . f 1 1 f f f 1 1 f . . . . . 
                    . . f 1 1 1 1 1 1 1 f . . . . . 
                    . f 1 1 1 1 1 1 1 1 1 f . . . . 
                    . f 1 f f 1 f f 1 1 1 f . . . . 
                    . f 1 f f 1 f f 1 1 1 f . . . . 
                    . f 1 f f 1 f f 1 1 1 f . . . . 
                    . f 1 1 1 1 1 1 1 1 1 f . . . . 
                    . . f 1 1 1 1 1 1 1 f . . . . . 
                    . . . f b b b b b f . . . . . . 
                    . . . f b b b b b f . . . . . . 
                    . . . f b b f b b f . . . . . . 
                    . . . f b b f f b f . . . . . . 
                    . . . f b f f f b f . . . . . . 
                    . . . . f f . f f . . . . . . . 
                    `)
            } else {
                if (r == 0) {
                    animation.runImageAnimation(
                    mySprite,
                    [img`
                        ...........f1f..f1f.....
                        ...........f11ff11f.....
                        ...........f11fff11f....
                        ...........f1111111f....
                        ..........f111111111f...
                        ..........f1ff1ff111f...
                        ..........f1ff1ff111f...
                        .......cc.f1ff1ff111f...
                        .......cdcf111111111f...
                        .......cddcf1111111f....
                        ........cddcfbbbbbf.....
                        .........cddcfbbbbf.....
                        ..........cdcffbbbf.....
                        ..........cccfffbbf.....
                        ............ffffbbf.....
                        .............ff.ff......
                        `,img`
                        ...........f1f..f1f.....
                        ...........f11ff11f.....
                        ...........f11fff11f....
                        ...........f1111111f....
                        ..........f111111111f...
                        ..........f1ff1ff111f...
                        ..........f1ff1ff111f...
                        ..........f1ff1ff111f...
                        ......cc..f111111111f...
                        ......cdcc.f1111111f....
                        ......ccddccfbbbbbf.....
                        ........cdddcfbbbbf.....
                        .........ccdcffbbbf.....
                        ..........cccfffbbf.....
                        .............fffbbf.....
                        .............ff.ff......
                        `,img`
                        ...........f1f..f1f.....
                        ...........f11ff11f.....
                        ...........f11fff11f....
                        ...........f1111111f....
                        ..........f111111111f...
                        ..........f1ff1ff111f...
                        ..........f1ff1ff111f...
                        ..........f1ff1ff111f...
                        ..........f111111111f...
                        ...........f1111111f....
                        ............cbbbbbf.....
                        ......cccccccfbbbbf.....
                        .......dddddcffbbbf.....
                        ........cccccfffbbf.....
                        ............cfffbbf.....
                        .............ff.ff......
                        `,img`
                        ...........f1f..f1f.....
                        ...........f11ff11f.....
                        ...........f11fff11f....
                        ...........f1111111f....
                        ..........f111111111f...
                        ..........f1ff1ff111f...
                        ..........f1ff1ff111f...
                        ..........f1ff1ff111f...
                        ..........f111111111f...
                        ...........f1111111f....
                        ............fbbbbbf.....
                        ...........cccbbbbf.....
                        ...........cdcfbbbf.....
                        ..........cddcffbbf.....
                        .........cddcfffbbf.....
                        ........cddc.ff.ff......
                        `],
                    100,
                    false
                    )
                    pause(500)
                    mySprite.setImage(img`
                        . . f 1 f . . f 1 f . . . . . . 
                        . . f 1 1 f f 1 1 f . . . . . . 
                        . . f 1 1 f f f 1 1 f . . . . . 
                        . . f 1 1 1 1 1 1 1 f . . . . . 
                        . f 1 1 1 1 1 1 1 1 1 f . . . . 
                        . f 1 f f 1 f f 1 1 1 f . . . . 
                        . f 1 f f 1 f f 1 1 1 f . . . . 
                        . f 1 f f 1 f f 1 1 1 f . . . . 
                        . f 1 1 1 1 1 1 1 1 1 f . . . . 
                        . . f 1 1 1 1 1 1 1 f . . . . . 
                        . . . f b b b b b f . . . . . . 
                        . . . f b b b b b f . . . . . . 
                        . . . f b b f b b f . . . . . . 
                        . . . f b b f f b f . . . . . . 
                        . . . f b f f f b f . . . . . . 
                        . . . . f f . f f . . . . . . . 
                        `)
                } else {
                    animation.runImageAnimation(
                    mySprite,
                    [img`
                        .....f1f..f1f...........
                        .....f11ff11f...........
                        ....f11fff11f...........
                        ....f1111111f...........
                        ...f111111111f..........
                        ...f111ff1ff1f..........
                        ...f111ff1ff1f..........
                        ...f111ff1ff1f.cc.......
                        ...f111111111fcdc.......
                        ....f1111111fcddc.......
                        .....fbbbbbfcddc........
                        .....fbbbbfcddc.........
                        .....fbbbffcdc..........
                        .....fbbfffccc..........
                        .....fbbffff............
                        ......ff.ff.............
                        `,img`
                        .....f1f..f1f...........
                        .....f11ff11f...........
                        ....f11fff11f...........
                        ....f1111111f...........
                        ...f111111111f..........
                        ...f111ff1ff1f..........
                        ...f111ff1ff1f..........
                        ...f111ff1ff1f..........
                        ...f111111111f..cc......
                        ....f1111111f.ccdc......
                        .....fbbbbbfccddcc......
                        .....fbbbbfcdddc........
                        .....fbbbffcdcc.........
                        .....fbbfffccc..........
                        .....fbbfff.............
                        ......ff.ff.............
                        `,img`
                        .....f1f..f1f...........
                        .....f11ff11f...........
                        ....f11fff11f...........
                        ....f1111111f...........
                        ...f111111111f..........
                        ...f111ff1ff1f..........
                        ...f111ff1ff1f..........
                        ...f111ff1ff1f..........
                        ...f111111111f..........
                        ....f1111111f...........
                        .....fbbbbbc............
                        .....fbbbbfccccccc......
                        .....fbbbffcddddd.......
                        .....fbbfffccccc........
                        .....fbbfffc............
                        ......ff.ff.............
                        `,img`
                        .....f1f..f1f...........
                        .....f11ff11f...........
                        ....f11fff11f...........
                        ....f1111111f...........
                        ...f111111111f..........
                        ...f111ff1ff1f..........
                        ...f111ff1ff1f..........
                        ...f111ff1ff1f..........
                        ...f111111111f..........
                        ....f1111111f...........
                        .....fbbbbbf............
                        .....fbbbbccc...........
                        .....fbbbfcdc...........
                        .....fbbffcddc..........
                        .....fbbfffcddc.........
                        ......ff.ff.cddc........
                        `],
                    100,
                    false
                    )
                    pause(500)
                    mySprite.setImage(img`
                        . . . . . f 1 f . . f 1 f . . . 
                        . . . . . f 1 1 f f 1 1 f . . . 
                        . . . . f 1 1 f f f 1 1 f . . . 
                        . . . . f 1 1 1 1 1 1 1 f . . . 
                        . . . f 1 1 1 1 1 1 1 1 1 f . . 
                        . . . f 1 1 1 f f 1 f f 1 f . . 
                        . . . f 1 1 1 f f 1 f f 1 f . . 
                        . . . f 1 1 1 f f 1 f f 1 f . . 
                        . . . f 1 1 1 1 1 1 1 1 1 f . . 
                        . . . . f 1 1 1 1 1 1 1 f . . . 
                        . . . . . f b b b b b f . . . . 
                        . . . . . f b b b b b f . . . . 
                        . . . . . f b b f b b f . . . . 
                        . . . . . f b f f b b f . . . . 
                        . . . . . f b f f f b f . . . . 
                        . . . . . . f f . f f . . . . . 
                        `)
                }
            }
        }
    }
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        vy = -85
        e = 0
    }
})
let b = 0
let e = 0
let vy = 0
let r = 0
let mySprite: Sprite = null
scene.setBackgroundImage(img`
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff99d99bbbbbcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff99ddbdd66168bcccccc9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff999ddbbbd66888111ccccccb99fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff9966ddbbbb6688811818ccccccbbc99fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdd69dddbbb66618881888818818cccccbe9fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffddd96dd6b6dbd68888888888888888cccccc99fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffdbbd9666666dbb668886888888cccccccccccccc9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffdbbb99666966d68866888888cccccccccccccccccc69ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffdbbb999669666666888888888ccccbbbcc8bcccccccccc9fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffdbbb999666666666888888888cbbcbe8bbbcbcccccbbcccb9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffff9bbb999666666666688888888bccb888888bbbbb88888bcccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffdbbb999669666666866888868bbbbb8888888ccc888b88bbc8cccffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffdbbb9d99ddd666668868888688bbcb888888888bc888bcc8bc886c9fffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbddd966666888688888888888888b88888888888cc8ccc886c9ffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffdbbbbbbdd6966666666868888888888bbdbbebb8888888888bcc8c86c9fffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffff9bbdbddd6666666666888688868888ddddddddde8888888888bccbbccccfffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffff9dbb9dd666666666668868888888bddddddbdbbddcccccd88b8ebccbbbbc9ffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffdd99999666666666668868888888bdddddbbbbbdbbbccccccb8bbbccc8bbb9fffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffff9dd99996696966666666668888bbbdddddbbbddbbbbbbbbbcccc8bcccbb8bbcfffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffff9d999996666966666668688888bbdddbbbbdbbbbbbbbbbbcccccc8bbccc88bc9ffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffff99999999666996696668868868bbdddddbbbdbbbbbbbbbbbbcbccc88bcccc88c6ffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffff999996696669666966d8868666bddbbbddbbdbbbbbbbbbbbbcccccc88bbccc8869fffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffff9999996699669666666d6688668bddbbdbbbbbbbbbbbbbbbbbccccccc88bcccc866fffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffff9dd999669966666666666688668bdddbbbbbbbbbbbbbbbbbbbccccccc888bbccc669ffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffff999999669d69666666666688868bddbbbdbbbbbbbbbbbbbbbbcccccccc888bbcc869ffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffff99999996ddd69666666688888868ddbddbbbbbbbbbbbbbbbbbbccccccccc888888866ffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffff999999969ddd6669666688688888bbbbbbbbbbbbbbbbbbbbbbbbccbccccc8888888869fffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffff99999966ddddd669666688888888bbbbbbbbbbbbbbbbbbbbbbbcbccccccccc88888869fffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff999bb99666dddd6666666668886888bbbbbbbbbbbbbbbbbbbbbbcccccccccccc8888889fffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff99bbbb966696666666666888886888bbbbbbbbbbbbbbbbbbbbbbcbccccccccccc888886fffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff99bbdbb666969666666668888868888bbbbbbbbbbbbbbbbbbbbccbccccccccccc8888869ffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff99dbbbbb6696966666666668886868888bbbbeb888bbbbbbbbbcccccccccccccc8888869ffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff99bbbbbbe6969666666666888888888888888888888bbbbbbbbccccccccccccc88888869ffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff9bbbbbccbc66966666666688888688888888888d888ebbbbbbbcccccccccccbb88888869ffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff9bbbbbbbbcc69996666688668886888888dd88dbbd88bbbbbbbccccccccccceb88888869ffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff9bbbbbbbbccc999966668868888888888ddddbbbbd88cbbbbbbbbccccccccc8888888869ffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff9ebbbbcccccccc9966666688888888888888ddbbbb888bbbbbbbbccccccccc8888888869ffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff9bbbbbccccccccc666666888866888888888dddddbdd88bbbbbbccccccccc88888888bb9ffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffbbbbbbcccccccccc6666688888888888888888d8888888bbbbbbccccccccc88888888bb9ffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff9dbbbbccbbccccccb666688868888888888888888888888bbbbbccccccccc888888888b9ffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff9dbbbbbbbbcccccbb66666688888888888888888888888bbbbccccccccccc88888888869ffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff9bbbbbbbcccccccb666666688888888888888888888888bbbbcccccccccc888888888869ffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff9bbbbbbbccccccbb666666688888888888888888888888bbbbcccccccccc88888888886fffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff99bbbbbbbbccccb6666668888888888888888888888888bbbbcbcccccccc88888888886fffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffff99dbbbcbbccccb6666668888888888888888888888888bbbbbccccccccc888cc888869fffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffff99dbbbcccccccc6666668688688888888888888888888bbbbccccccccc8888cc888869fffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffff999bbbbbccccbc6666666688688888888888888888888bbbbcccccccc88888dd88886ffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffff969bbbbbbcccc69666666668688868888888888888888bbbbccccccc88888bd888886ffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffff99bbbbcccccc696bb668888888868888888888888888bbbcccccccc8888bbd888869ffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffff9999bbbcccc9666dbbb8888888888888888888888888ccbcccccccc8888bc888886fffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffff699bbbbccc966966bbb8888888888888888888888888bbbbccccc88888bcc88869fffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffff9999bbcccc666666dbbdd88888888688888888888888bbcccccc88888888888669fffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffff9699dbcccc66666666bb6d8888888688888888888888bbcccccc8888888888869ffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffff9696bbbcc66666666dbbd6886868888888888888888bbcbccc8888888888d669ffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffff999ebbccc666666666dbb8868888688888888888888bbbccc8888888889b69fffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffff969ccbcc66996666666bbb868888888888888888888bbbc888888888888b6ffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffff96ccccc966966666666bb8688666888888888888888b8888888888888699ffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffff99ccbc996666666666dbb6888668888888888888888888888888888869fffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffff969ccb9666666666666dbb88866888888888888888888888888888869ffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffff969ccc6696666666666dd8888668888888888888888888888888866fffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffff969cc9669666966d66dd8888868888888888888888888bb8888669fffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffff96ccc66699669dddd888868888888888888888888888be888669ffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffff96c66669966666dd88886666668888888888888888dd888669fffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffff96966669966ddd686886868888888888888888888d888669ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffff969666696666666688686888888888888888888888669ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffff9966966966666666886888888888888886888888669fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff9699996666666888888888888888888118888699ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff969996666668888881188888888881888669ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff996999666688881818888888881886669ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff9961161186618811188886116699ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff99161111611118111666699fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff9999661166669999ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff999999999fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    `)
tiles.setCurrentTilemap(tilemap`niveau1`)
mySprite = sprites.create(img`
    . . f 1 f . . . . . . f 1 f . . 
    . . f 1 1 f . . . . f 1 1 f . . 
    . f 1 1 f . . . . . . f 1 1 f . 
    . f 1 1 f f f f f f f f 1 1 f . 
    . f 1 1 f 1 1 1 1 1 1 f 1 1 f . 
    . . f 1 1 1 1 1 1 1 1 1 1 f . . 
    . . f 1 1 1 1 1 1 1 1 1 1 f . . 
    . . f 1 1 f f 1 1 f f 1 1 f . . 
    . . f 1 1 f f 1 1 f f 1 1 f . . 
    . . f 1 1 f f 1 1 f f 1 1 f . . 
    . . . f 1 1 1 1 1 1 1 1 f . . . 
    . . . . f b b b b b b f . . . . 
    . . . . f b b b f b b f . . . . 
    . . . . f b b f f b b f . . . . 
    . . . . f b f f f f b f . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
info.setLife(5)
forever(function () {
    scene.cameraFollowSprite(mySprite)
})
forever(function () {
    mySprite.vy = vy
})
forever(function () {
    vy += 2
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        pauseUntil(() => b >= 20 && (e >= 30 || (mySprite.isHittingTile(CollisionDirection.Top) || !(controller.A.isPressed()))))
        vy = 30
    }
})
forever(function () {
    e += 1
})
forever(function () {
    if (controller.left.isPressed() && !(controller.right.isPressed())) {
        mySprite.vx = -80
        if (controller.up.isPressed() && b >= 60) {
            mySprite.setVelocity(-200, 0)
            vy = 0
            b = 0
            pauseUntil(() => b >= 15)
        }
    } else {
        if (controller.right.isPressed() && !(controller.left.isPressed())) {
            mySprite.vx = 80
            if (controller.up.isPressed() && b >= 60) {
                mySprite.setVelocity(200, 0)
                vy = 0
                b = 0
                pauseUntil(() => b >= 15)
            }
        } else {
            mySprite.vx = 0
        }
    }
})
forever(function () {
    b += 1
})
forever(function () {
    if (controller.left.isPressed() && !(controller.right.isPressed())) {
        animation.runImageAnimation(
        mySprite,
        [img`
            . . f 1 f . . f 1 f . . . . . . 
            . . f 1 1 f f 1 1 f . . . . . . 
            . . f 1 1 f f f 1 1 f . . . . . 
            . . f 1 1 1 1 1 1 1 f . . . . . 
            . f 1 1 1 1 1 1 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 1 1 1 1 1 1 1 1 f . . . . 
            . . f 1 1 1 1 1 1 1 f . . . . . 
            . . . f f b b b b f . . . . . . 
            . . . . f b b b b f . . . . . . 
            . . . . f b f b b b f . . . . . 
            . . . . f b f f b b f . . . . . 
            . . . . . f f f f b f . . . . . 
            . . . . . f f . f f . . . . . . 
            `,img`
            . . . f . . . . f . . . . . . . 
            . . f 1 f . . f 1 f . . . . . . 
            . . f 1 1 f f 1 1 f . . . . . . 
            . . f 1 1 f f f 1 1 f . . . . . 
            . . f 1 1 1 1 1 1 1 f . . . . . 
            . f 1 1 1 1 1 1 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 1 1 1 1 1 1 1 1 f . . . . 
            . . f 1 1 1 1 1 1 1 f . . . . . 
            . . . f f b b b b f . . . . . . 
            . . . . f b f b b b f . . . . . 
            . . . . f b f f b b f . . . . . 
            . . . . f f f f f b f . . . . . 
            . . . . f f . . f f . . . . . . 
            `,img`
            . . f 1 f . . f 1 f . . . . . . 
            . . f 1 1 f f 1 1 f . . . . . . 
            . . f 1 1 f f f 1 1 f . . . . . 
            . . f 1 1 1 1 1 1 1 f . . . . . 
            . f 1 1 1 1 1 1 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 1 1 1 1 1 1 1 1 f . . . . 
            . . f 1 1 1 1 1 1 1 f . . . . . 
            . . . f f b b b b f . . . . . . 
            . . . . f b b b b f . . . . . . 
            . . . . f b f b b b f . . . . . 
            . . . . f b f f b b f . . . . . 
            . . . . . f f f f b f . . . . . 
            . . . . . . . f f f . . . . . . 
            `,img`
            . . . f . . . . f . . . . . . . 
            . . f 1 f . . f 1 f . . . . . . 
            . . f 1 1 f f 1 1 f . . . . . . 
            . . f 1 1 f f f 1 1 f . . . . . 
            . . f 1 1 1 1 1 1 1 f . . . . . 
            . f 1 1 1 1 1 1 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 1 1 1 1 1 1 1 1 f . . . . 
            . . f 1 1 1 1 1 1 1 f . . . . . 
            . . . f f b b b b f . . . . . . 
            . . . . f b f b b b f . . . . . 
            . . . . f b f f b b f . . . . . 
            . . . . f f f f f b f . . . . . 
            . . . . f f . . f f . . . . . . 
            `],
        200,
        true
        )
        pauseUntil(() => controller.up.isPressed() && b >= 60 || (controller.right.isPressed() || (!(controller.left.isPressed()) || !(mySprite.isHittingTile(CollisionDirection.Bottom)))))
        if (controller.up.isPressed() && b >= 60) {
            b = 0
            while (b < 25) {
                animation.stopAnimation(animation.AnimationTypes.All, mySprite)
                mySprite.setImage(img`
                    ..f....f.................
                    .f1f..f1f................
                    .f11ff11f........ffff....
                    .f11fff11f.....ffbbbbf...
                    .f1111111f..fffbbbbbf....
                    f111111111ffbbbbffff.....
                    f1ff1ff111fbbfbbbbbf.....
                    f1ff1ff111fffbbbfffff....
                    f1ff1ff111fbbbffbbbbbf...
                    f111111111fffbbbbbbbf....
                    .f1111111fbbbfbffbbf.....
                    ..fffffff.ffbbbbbffff....
                    ............ffbbbbbbbf...
                    ..............ffffbbf....
                    ..................ff.....
                    .........................
                    `)
            }
            pauseUntil(() => b >= 30)
        }
        animation.stopAnimation(animation.AnimationTypes.All, mySprite)
        mySprite.setImage(img`
            . . f 1 f . . f 1 f . . . . . . 
            . . f 1 1 f f 1 1 f . . . . . . 
            . . f 1 1 f f f 1 1 f . . . . . 
            . . f 1 1 1 1 1 1 1 f . . . . . 
            . f 1 1 1 1 1 1 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 1 1 1 1 1 1 1 1 f . . . . 
            . . f 1 1 1 1 1 1 1 f . . . . . 
            . . . f b b b b b f . . . . . . 
            . . . f b b b b b f . . . . . . 
            . . . f b b f b b f . . . . . . 
            . . . f b b f f b f . . . . . . 
            . . . f b f f f b f . . . . . . 
            . . . . f f . f f . . . . . . . 
            `)
        r = 0
    } else {
        if (controller.right.isPressed() && !(controller.left.isPressed())) {
            animation.runImageAnimation(
            mySprite,
            [img`
                . . . . . . f 1 f . . f 1 f . . 
                . . . . . . f 1 1 f f 1 1 f . . 
                . . . . . f 1 1 f f f 1 1 f . . 
                . . . . . f 1 1 1 1 1 1 1 f . . 
                . . . . f 1 1 1 1 1 1 1 1 1 f . 
                . . . . f 1 1 1 f f 1 f f 1 f . 
                . . . . f 1 1 1 f f 1 f f 1 f . 
                . . . . f 1 1 1 f f 1 f f 1 f . 
                . . . . f 1 1 1 1 1 1 1 1 1 f . 
                . . . . . f 1 1 1 1 1 1 1 f . . 
                . . . . . . f b b b b f f . . . 
                . . . . . . f b b b b f . . . . 
                . . . . . f b b b f b f . . . . 
                . . . . . f b b f f b f . . . . 
                . . . . . f b f f f f . . . . . 
                . . . . . . f f . f f . . . . . 
                `,img`
                . . . . . . . f . . . . f . . . 
                . . . . . . f 1 f . . f 1 f . . 
                . . . . . . f 1 1 f f 1 1 f . . 
                . . . . . f 1 1 f f f 1 1 f . . 
                . . . . . f 1 1 1 1 1 1 1 f . . 
                . . . . f 1 1 1 1 1 1 1 1 1 f . 
                . . . . f 1 1 1 f f 1 f f 1 f . 
                . . . . f 1 1 1 f f 1 f f 1 f . 
                . . . . f 1 1 1 f f 1 f f 1 f . 
                . . . . f 1 1 1 1 1 1 1 1 1 f . 
                . . . . . f 1 1 1 1 1 1 1 f . . 
                . . . . . . f b b b b f f . . . 
                . . . . . f b b b f b f . . . . 
                . . . . . f b b f f b f . . . . 
                . . . . . f b f f f f f . . . . 
                . . . . . . f f . . f f . . . . 
                `,img`
                . . . . . . f 1 f . . f 1 f . . 
                . . . . . . f 1 1 f f 1 1 f . . 
                . . . . . f 1 1 f f f 1 1 f . . 
                . . . . . f 1 1 1 1 1 1 1 f . . 
                . . . . f 1 1 1 1 1 1 1 1 1 f . 
                . . . . f 1 1 1 f f 1 f f 1 f . 
                . . . . f 1 1 1 f f 1 f f 1 f . 
                . . . . f 1 1 1 f f 1 f f 1 f . 
                . . . . f 1 1 1 1 1 1 1 1 1 f . 
                . . . . . f 1 1 1 1 1 1 1 f . . 
                . . . . . . f b b b b f f . . . 
                . . . . . . f b b b b f . . . . 
                . . . . . f b b b f b f . . . . 
                . . . . . f b b f f b f . . . . 
                . . . . . f b f f f f . . . . . 
                . . . . . . f f f . . . . . . . 
                `,img`
                . . . . . . . f . . . . f . . . 
                . . . . . . f 1 f . . f 1 f . . 
                . . . . . . f 1 1 f f 1 1 f . . 
                . . . . . f 1 1 f f f 1 1 f . . 
                . . . . . f 1 1 1 1 1 1 1 f . . 
                . . . . f 1 1 1 1 1 1 1 1 1 f . 
                . . . . f 1 1 1 f f 1 f f 1 f . 
                . . . . f 1 1 1 f f 1 f f 1 f . 
                . . . . f 1 1 1 f f 1 f f 1 f . 
                . . . . f 1 1 1 1 1 1 1 1 1 f . 
                . . . . . f 1 1 1 1 1 1 1 f . . 
                . . . . . . f b b b b f f . . . 
                . . . . . f b b b f b f . . . . 
                . . . . . f b b f f b f . . . . 
                . . . . . f b f f f f f . . . . 
                . . . . . . f f . . f f . . . . 
                `],
            200,
            true
            )
            pauseUntil(() => controller.up.isPressed() && b >= 60 || (controller.left.isPressed() || (!(controller.right.isPressed()) || !(mySprite.isHittingTile(CollisionDirection.Bottom)))))
            if (controller.up.isPressed() && b >= 60) {
                b = 0
                while (b < 25) {
                    animation.stopAnimation(animation.AnimationTypes.All, mySprite)
                    mySprite.setImage(img`
                        .................f....f..
                        ................f1f..f1f.
                        ....ffff........f11ff11f.
                        ...fbbbbff.....f11fff11f.
                        ....fbbbbbfff..f1111111f.
                        .....ffffbbbbff111111111f
                        .....fbbbbbfbbf111ff1ff1f
                        ....fffffbbbfff111ff1ff1f
                        ...fbbbbbffbbbf111ff1ff1f
                        ....fbbbbbbbfff111111111f
                        .....fbbffbfbbbf1111111f.
                        ....ffffbbbbbff.fffffff..
                        ...fbbbbbbbff............
                        ....fbbffff..............
                        .....ff..................
                        .........................
                        `)
                }
                pauseUntil(() => b >= 30)
            }
            animation.stopAnimation(animation.AnimationTypes.All, mySprite)
            mySprite.setImage(img`
                . . . . . f 1 f . . f 1 f . . . 
                . . . . . f 1 1 f f 1 1 f . . . 
                . . . . f 1 1 f f f 1 1 f . . . 
                . . . . f 1 1 1 1 1 1 1 f . . . 
                . . . f 1 1 1 1 1 1 1 1 1 f . . 
                . . . f 1 1 1 f f 1 f f 1 f . . 
                . . . f 1 1 1 f f 1 f f 1 f . . 
                . . . f 1 1 1 f f 1 f f 1 f . . 
                . . . f 1 1 1 1 1 1 1 1 1 f . . 
                . . . . f 1 1 1 1 1 1 1 f . . . 
                . . . . . f b b b b b f . . . . 
                . . . . . f b b b b b f . . . . 
                . . . . . f b b f b b f . . . . 
                . . . . . f b f f b b f . . . . 
                . . . . . f b f f f b f . . . . 
                . . . . . . f f . f f . . . . . 
                `)
            r = 1
        } else {
        	
        }
    }
    if (r == 0 && vy >= 30 && !(mySprite.isHittingTile(CollisionDirection.Bottom))) {
        animation.stopAnimation(animation.AnimationTypes.All, mySprite)
        mySprite.setImage(img`
            . . . f . . . . f . . . . . . . 
            . . f 1 f . . f 1 f . . . . . . 
            . . f 1 1 f f 1 1 f . . . . . . 
            . . f 1 1 f f f 1 1 f . . . . . 
            . . f 1 1 1 1 1 1 1 f . . . . . 
            . f 1 1 1 1 1 1 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 f f 1 f f 1 1 1 f . . . . 
            . f 1 1 1 1 1 1 1 1 1 f . . . . 
            . . f 1 1 1 1 1 1 1 f . . . . . 
            . . f b b b f b b b f . . . . . 
            . f b b b f f f b b b f . . . . 
            . f b b b f f f f b b b f . . . 
            . . f f f f f f f f f f . . . . 
            . . . . f f . f f . . . . . . . 
            `)
        if (controller.up.isPressed() && b >= 60) {
            b = 0
            while (b < 25) {
                animation.stopAnimation(animation.AnimationTypes.All, mySprite)
                mySprite.setImage(img`
                    ..f....f.................
                    .f1f..f1f................
                    .f11ff11f........ffff....
                    .f11fff11f.....ffbbbbf...
                    .f1111111f..fffbbbbbf....
                    f111111111ffbbbbffff.....
                    f1ff1ff111fbbfbbbbbf.....
                    f1ff1ff111fffbbbfffff....
                    f1ff1ff111fbbbffbbbbbf...
                    f111111111fffbbbbbbbf....
                    .f1111111fbbbfbffbbf.....
                    ..fffffff.ffbbbbbffff....
                    ............ffbbbbbbbf...
                    ..............ffffbbf....
                    ..................ff.....
                    .........................
                    `)
            }
            pauseUntil(() => b >= 30)
        }
    } else {
        if (r == 1 && vy >= 30 && !(mySprite.isHittingTile(CollisionDirection.Bottom))) {
            animation.stopAnimation(animation.AnimationTypes.All, mySprite)
            mySprite.setImage(img`
                . . . . . f . . . . f . . . . . 
                . . . . f 1 f . . f 1 f . . . . 
                . . . . f 1 1 f f 1 1 f . . . . 
                . . . f 1 1 f f f 1 1 f . . . . 
                . . . f 1 1 1 1 1 1 1 f . . . . 
                . . f 1 1 1 1 1 1 1 1 1 f . . . 
                . . f 1 1 1 f f 1 f f 1 f . . . 
                . . f 1 1 1 f f 1 f f 1 f . . . 
                . . f 1 1 1 f f 1 f f 1 f . . . 
                . . f 1 1 1 1 1 1 1 1 1 f . . . 
                . . . f 1 1 1 1 1 1 1 f . . . . 
                . . . f b b b f b b b f . . . . 
                . . f b b b f f f b b b f . . . 
                . f b b b f f f f b b b f . . . 
                . . f f f f f f f f f f . . . . 
                . . . . . f f . f f . . . . . . 
                `)
            if (controller.up.isPressed() && b >= 60) {
                b = 0
                while (b < 25) {
                    animation.stopAnimation(animation.AnimationTypes.All, mySprite)
                    mySprite.setImage(img`
                        .................f....f..
                        ................f1f..f1f.
                        ....ffff........f11ff11f.
                        ...fbbbbff.....f11fff11f.
                        ....fbbbbbfff..f1111111f.
                        .....ffffbbbbff111111111f
                        .....fbbbbbfbbf111ff1ff1f
                        ....fffffbbbfff111ff1ff1f
                        ...fbbbbbffbbbf111ff1ff1f
                        ....fbbbbbbbfff111111111f
                        .....fbbffbfbbbf1111111f.
                        ....ffffbbbbbff.fffffff..
                        ...fbbbbbbbff............
                        ....fbbffff..............
                        .....ff..................
                        .........................
                        `)
                }
                pauseUntil(() => b >= 30)
            }
        } else {
        	
        }
    }
})
forever(function () {
	
})
